### ISSUE TITLE
Some observations on using cuPDLP-C with HiGHS

### ISSUE THREAD

**Issue by jajhall** [COPT-Public/cuPDLP-C#10]
I've managed to get cuPDLP-C (for CPU) running on my Linux PC, and here are some observations

- Make it clear in the README that the precompiled Github download of HiGHS should be used
- The following command in the README is incorrect: it should have "..". Using just

cmake --build . --target plc

I get

Error: could not load cache

- The HiGHS binaries are built without zlib support, so the  hard-coded `char *fname = "./example/afiro.mps.gz";` can't be read. Hence `bin/plc` can only be run successfully using the `-fname` command line parameter. Hence I've replaced `afiro.mps.gz` locally by `afiro.mps`, and suggest that you do the same

My modified `README.md` and `mps_highs.c` are in the following file - which unzips into the same folder as the one in which it is stored

[highs-mods.zip](https://github.com/COPT-Public/cuPDLP-C/files/13917795/highs-mods.zip)

**Comment by bzhangcw** [comment]
Dear Dr. Hall, 
thanks for your comments on this version built on HiGHS. We have included a download link to https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases; otherwises someone may use the static version instead.

It is weird to see `cmake --build . --target plc` does not work; we are fine on both Linux and Mac. Thanks for the suggestion on zlib support.  😀

**Comment by jajhall** [comment]
With "cmake --build . --target plc", it works for me if run from the directory below 'build', of course

**Comment by bzhangcw** [comment]
Perfect!
