### ISSUE TITLE
Warm start performance

### ISSUE THREAD

**Issue by richardrl** [COPT-Public/cuPDLP-C#18]
How much computation time savings does warm starting have in PDLP?

For example, in an MPC type setting where the bounds and costs, and even the constraint matrix, slightly change each time.

**Comment by bzhangcw** [comment]
@richardrl Thanks for the question. Intuitively if PDLP (and also IPM) warm starts at some previous solution $x$ for a slightly perturbed problem, then one can imagine if the perturbation is sufficiently small, $x$ shall be close to the solution set. Theoretically, this relates to the ``local'' convergence and whether or not your perturbation changes the active set (active inequalities). I would suggest a reference to the latest refined analysis of PDLP, e.g.,
[1] Lu, H., Yang, J.: On the Geometry and Refined Rate of Primal-Dual Hybrid Gradient for Linear Programming, http://arxiv.org/abs/2307.03664, (2023)
