### ISSUE TITLE
Corrected Dual Objective

### ISSUE THREAD

**Issue by stumarcus314** [COPT-Public/cuPDLP-C#19]
Do cuPDLP-C and cuPDLP.jl compute a corrected dual objective, which is a feasible lower bound of the true objective value? The corrected dual objective is computed by the Julia implementation of PDLP in FirstOrderLp.jl and by OR-Tools PDLP.

https://developers.google.com/optimization/lp/pdlp_math#reduced_costs_dual_residuals_and_the_corrected_dual_objective
https://github.com/jinwen-yang/cuPDLP.jl
https://github.com/google-research/FirstOrderLp.jl/blob/205e0e79985a6b48add6420f242cd812e402edd0/src/solve_log.jl#L84
https://github.com/search?q=repo%3Agoogle%2For-tools+corrected_dual_objective&type=code

**Comment by bzhangcw** [comment]
Thanks for your comments. Currently, the dual objective is a direct calculation from dual solution $y$, we do not compute a corrected one for now.
