### ISSUE TITLE
Speed comparison for milp problems

### ISSUE THREAD

**Issue by Aguang277** [COPT-Public/cuPDLP-C#20]
I have mainly used gurobi solver to solve MILP problems before, and I would like to know how fast this solver using gpu can solve MILP problems compared to it?

**Comment by SkyLiu0** [comment]
Thank you for your interest in our solver. Currently, cuPDLP-C is developed as a first-order LP solver that can support CPU and GPU. In MILP, the dual simplex method more often solves the LP subproblems. If you are looking for other high-performance MILP solvers, we recommend you to try COPT (https://www.shanshu.ai/copt), which contains both a more user-friendly cuPDLP-C and a state-of-the-art MILP solver.
